# Generated by Django 6.1 on 2026-08-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('id_pokemon', models.IntegerField(verbose_name='Número da Pokédex')),
                ('tipos', models.CharField(max_length=50, verbose_name='Tipo primário')),
                ('altura', models.CharField(blank=True, default='', max_length=20, verbose_name='Altura')),
                ('peso', models.CharField(blank=True, default='', max_length=20, verbose_name='Peso')),
                ('habilidades', models.CharField(blank=True, default='', max_length=150, verbose_name='Habilidade')),
                ('hp', models.IntegerField(default=0, verbose_name='HP')),
                ('ataque', models.IntegerField(default=0, verbose_name='Ataque')),
                ('defesa', models.IntegerField(default=0, verbose_name='Defesa')),
                ('velocidade', models.IntegerField(default=0, verbose_name='Velocidade')),
                ('sprite_url', models.URLField(blank=True, default='', verbose_name='Imagem')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('favorito', models.BooleanField(default=False, verbose_name='Favorito')),
                ('capturado', models.BooleanField(default=False, verbose_name='Capturado')),
                ('data_captura', models.DateField(auto_now_add=True, verbose_name='Adicionado em')),
            ],
        ),
    ]
