# Generated by Django 6.1 on 2026-08-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='sprite_url',
            field=models.CharField(blank=True, default='', verbose_name='Imagem'),
        ),
    ]
