# Generated by Django 6.1 on 2026-08-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0002_alter_pokemon_sprite_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='habilidades',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='tipos',
            field=models.JSONField(default=list),
        ),
    ]
